files: "^(scanner/.*)$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming
          - flake8-bandit
          - dlint

default_stages:
  - commit
  - push
